import os

from fridacli.chatbot.predefined_phrases import (
    ERROR_MISSING_CONFIGFILE,
    ERROR_INVALID_COMMAND,
    INTERRUPT_CHAT,
    WELCOME_PANEL_MESSAGE,
)
from fridacli.chatfiles.file_manager import FileManager
from fridacli.config.env_vars import config_file_exists, get_config_vars, get_username
from fridacli.commands.subcommands.callbacks import (
    get_completions,
    SUBCOMMANDS_CALLBACKS,
)
from fridacli.interface.bot_console import BotConsole
from fridacli.interface.styles import print_padding
from fridacli.interface.system_console import SystemConsole
from fridacli.interface.user_console import UserConsole

from chatbot.chatbot import ChatbotAgent
from fridacli.fridaCoder.frida_coder import FridaCoder
from .predefined_phrases import (
    execution_result,
    error_chat_prompt,
    ERROR_CONFIRMATION_MESSAGE,
    LANG_NOT_FOUND,
    RUN_CONFIRMATION_MESSAGE,
)

system = SystemConsole()
frida_coder = FridaCoder()
file_manager = FileManager()



def start_panel() -> None:
    """"""
    system.print_panel(
        message=WELCOME_PANEL_MESSAGE, title="FRIDA CLI", subtitle=INTERRUPT_CHAT
    )


def get_command_parts(command_string: str) -> tuple[str, list[str]]:
    """"""
    words = command_string.split(" ")
    command = words[0]
    command_args = words[1:] if len(words) > 1 else []
    return command, command_args


def exec_subcommand(subcommand: str, *args):
    """"""
    if subcommand not in SUBCOMMANDS_CALLBACKS:
        system.notification(ERROR_INVALID_COMMAND(subcommand))
    else:
        SUBCOMMANDS_CALLBACKS[subcommand]["execute"](
            *args, system_console=system, file_manager=file_manager
        )
        print_padding()


def chat_session() -> None:
    """"""
    chatting = True
    user = UserConsole(username=get_username())
    chatbot_console = BotConsole()
    chatbot_agent = ChatbotAgent()

    start_panel()

    while chatting:
        try:
            current_dir = os.path.basename(os.getcwd())
            completions = get_completions()
            user_input = user.user_input(
                current_dir=current_dir,
                completer=completions,
                open_folder=file_manager.get_folder_status(),
            )
            is_empty = len(user_input.replace(" ", "")) == 0
            is_command = user_input.startswith("!")

            # If it's an empty input
            if is_empty:
                print_padding()
                continue

            # If the input is a command
            if is_command:
                command, command_args = get_command_parts(user_input)
                exec_subcommand(command, *command_args)

            else:
                response = chatbot_agent.chat(user_input)

                # Chatbot response from the user input
                # print("respose", response)
                chatbot_console.response(response, streaming=True)
                # print(response)
                # Check if the text has code blocks
                # Ask for confirmation to run the code
                run_confirmation = system.confirm(RUN_CONFIRMATION_MESSAGE)
                if run_confirmation:
                    # Run the code generated by the chat bot
                    responses = frida_coder.run(response)
                    if len(responses) > 0:
                        for response in responses:
                            # If errors are detected in the code, prompt for confirmation before submitting feedback to the chat bot
                            if response["status"] == "ERROR":
                                chat_execution_response = execution_result(response)
                                chatbot_console.response(
                                    chat_execution_response, streaming=True
                                )
                                confirm = system.confirm(ERROR_CONFIRMATION_MESSAGE)
                                if confirm:
                                    result = chatbot_agent.chat(
                                        error_chat_prompt(
                                            response["code"], response["result"]
                                        )
                                    )
                                    chatbot_console.response(result, streaming=True)
                            # If the is no errors show the result of the execution
                            elif response["status"] == "SUCCESS":
                                chat_execution_response = execution_result(response)
                                chatbot_console.response(
                                    chat_execution_response, streaming=True
                                )
                            # If an unknown code language is detected
                            else:
                                chatbot_console.response(LANG_NOT_FOUND, streaming=True)

        except KeyboardInterrupt:
            exec_subcommand("!exit")


def exec_chat(path: str | None, tokens: bool):
    """"""
    if not config_file_exists():
        system.notification(ERROR_MISSING_CONFIGFILE)
        return

    system.print("Initializing...", style="process", bottom=0)

    chat_session()
